plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

version = getSubprojectVersion(project)
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	accessWidenerPath = file('src/main/resources/taiyitist-access-wideners.accesswidener')
}

dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
	// The launcher already installs this version; also expose it to development and tests.
	implementation('net.minecrell:terminalconsoleappender:1.4.0') { transitive = false }
	annotationProcessor 'org.apache.logging.log4j:log4j-core:2.20.0'
	include(implementation("net.kyori:adventure-api:4.17.0"))
	include(implementation("net.kyori:adventure-key:4.17.0"))
	include(implementation("net.kyori:adventure-text-minimessage:4.17.0"))
	include(implementation("net.kyori:adventure-text-serializer-gson:4.17.0"))
	include(implementation("net.kyori:adventure-text-serializer-json:4.17.0"))
	include(implementation("net.kyori:adventure-text-serializer-legacy:4.17.0"))
	include(implementation("net.kyori:adventure-text-serializer-plain:4.17.0"))
	include(implementation("net.kyori:adventure-text-serializer-ansi:4.17.0"))
	include(implementation("net.kyori:adventure-text-logger-slf4j:4.17.0"))
	include(implementation("net.kyori:ansi:1.0.3"))
	include(implementation("net.kyori:examination-api:1.3.0"))
	include(implementation("net.kyori:examination-string:1.3.0"))
	include(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${property("mixin_squared_version")}"))
}

test {
	useJUnitPlatform()
	systemProperty 'console.logConfig', rootProject.file('src/main/resources/log4j2_taiyitist.xml').absolutePath
	doFirst {
		systemProperty 'console.testClasspath', sourceSets.test.runtimeClasspath.asPath
	}
}
